Fixing testIterateID(org.wso2.carbon.esb.mediator.test.iterate.IterateIDTestCase): expected:<2> but was:<1> This is due to PF mediator changing message type from text/xml to application/xml